---
# tasks file for ansible-spectrum-control

- import_tasks: get_sc.yml
  tags: sc_get

- import_tasks: install_sc.yml
  tags: sc_install
  when:
    - not sc_upgrade | bool

- import_tasks: upgrade_sc.yml
  tags: sc_upgrade
  when:
    - sc_upgrade | bool

- import_tasks: finalize.yml
  tags: sc_finalize